### ISSUE TITLE
Infos to setup this project

### ISSUE THREAD

**Issue by riverstore** [Arag0rn/LibraryManagementSystem#1]
Hi!

First I'd like to say Thanks for this project, it's really helpfull to me. Can you please give some infos to setup this project: DB, login

Thanks a lot

**Comment by Arag0rn** [comment]
Hi, thanks for the appreciation. This project uses 'Code First' which means that when you start the project for the first time, the DB will create automatically for you. You must have IIS on a Windows machine. If you download Visual Studio 2013 Express for Web you will have the ability to run the project and you'll get the IIS. Through Visual Studio or SQL Server Management Studio you can insert your first admin credentials.

Think that's all.
Cheers!

**Comment by riverstore** [comment]
Hi! Thank for helping. I tried run Update-Database –force and it's also work. Thanks a gain for the great project
