### ISSUE TITLE
SQL DB table population query

### ISSUE THREAD

**Issue by vraghu1983** [Arag0rn/LibraryManagementSystem#2]
I set up the SQL DB - however - the authenitcating actions and controller tables are empty-  as a result of which i am unable to control the roles - how do i populate this properly so that i get a clean working model ?

**Comment by Arag0rn** [comment]
Here is the DB with some fictional data to start with. Just remove the .png extension at the end of the files, paste the files to your SQL Server directory and make sure your connection string is correct.

Cheers!
![librarymanagementsystem mdf mdf](https://cloud.githubusercontent.com/assets/7597295/6608009/3c7ad47e-c84c-11e4-8773-e5a27c7bc0e5.png)
![librarymanagementsystem mdf_log ldf](https://cloud.githubusercontent.com/assets/7597295/6608010/3c7bd43c-c84c-11e4-874a-5d370865be5b.png)

**Comment by Arag0rn** [comment]
Here is the right sequence to import your data and start using the database.
Cheers!

![1](https://cloud.githubusercontent.com/assets/7597295/6608193/aeb21b0a-c84d-11e4-9b1a-ac6caaa830e8.PNG)
![2](https://cloud.githubusercontent.com/assets/7597295/6608194/aeb2e972-c84d-11e4-89b1-b89f8cdeacc7.PNG)
![3](https://cloud.githubusercontent.com/assets/7597295/6608198/aeb5401e-c84d-11e4-8259-12a57bf53602.PNG)
![4](https://cloud.githubusercontent.com/assets/7597295/6608196/aeb4691e-c84d-11e4-961c-cdbb7de51c8c.PNG)
![5](https://cloud.githubusercontent.com/assets/7597295/6608195/aeb3470a-c84d-11e4-9e50-57cfbc5dbd6d.PNG)
![6](https://cloud.githubusercontent.com/assets/7597295/6608197/aeb4b3d8-c84d-11e4-9793-f109bd8c535e.PNG)
![7](https://cloud.githubusercontent.com/assets/7597295/6608199/aecb0b88-c84d-11e4-848f-56fd26579e13.PNG)

**Comment by kpkantaw** [comment]
Dont see sql db script. Can you upload that as well please.

**Comment by Arag0rn** [comment]
Sample for the first row from the first table- Users: 
INSERT INTO Users (PersonalNumber, Password, Email, Address, Birthday, DateIn, FirstName, LastName)
VALUES (1, 'admin', 'admin@mail.com', 'Somewhere', 28/2/1980, 28/2/2000, 'Admin', 'Admin')
GO

Follow the screenshot sequence and use the same values.

Cheers!
